## Работа с файлами в Google Colab

### Этап 1. Подгрузка файлов

#### Способ 1. Вручную через вкладку 'Файлы'

In [1]:
# демонстрация
# /content/titanic.csv - файл во временной папке, пока сессия работает (блокнот запоминает переменные)

#### Способ 2. Через модуль files библиотеки google.colab

In [2]:
# из библиотеки google.colab загружаем класс files
from google.colab import files

In [190]:
# применяем метод .upload() и записываем в переменную uploaded
# uploaded = files.upload()

In [96]:
# посмотрим на содержимое uploaded
# uploaded

#### Cпособ 3. Загрузка с google disk

In [97]:
from google.colab import files, drive # Сохранить из google colab или в google colab

In [98]:
# drive.mount('/content/drive') # загрузим с google диска

In [99]:
import pandas as pd

In [100]:
#Data Frame
# df = pd.read_csv('/content/drive/MyDrive/titanic.csv', sep=',')
# df

In [101]:
#Data Frame
# df = pd.read_csv('/content/drive/MyDrive/cars/cars.csv', sep=',')
# df

In [102]:
!gdown 1tYz4j2TGX5_fJ0qwvZvHs-lSUFamI6tt

Downloading...
From: https://drive.google.com/uc?id=1tYz4j2TGX5_fJ0qwvZvHs-lSUFamI6tt
To: /content/titanic.csv
100% 61.2k/61.2k [00:00<00:00, 90.0MB/s]

In [103]:
!gdown 1pIZgigx4FcKUPCxhj5zBwQmIQgHXqNg1

Downloading...
From: https://drive.google.com/uc?id=1pIZgigx4FcKUPCxhj5zBwQmIQgHXqNg1
To: /content/cars.csv
0.00B [00:00, ?B/s]

### Этап 2. Чтение файлов

#### Просмотр содержимого папки /content/

##### Команда `!ls`

In [104]:
# посмотрим на содержимое папки content
!ls

cars.csv  result.csv  sample_data  titanic.csv

In [105]:
# заглянем внутрь sample_data
!ls /content/sample_data/

anscombe.json		     california_housing_train.csv  mnist_train_small.csv
california_housing_test.csv  mnist_test.csv		   README.md

#### Чтение из переменной uploaded

In [106]:
# посмотрим на тип значений словаря uploaded
# type(uploaded['titanic.csv'])

Пример работы с объектом bytes

In [107]:
# обратимся к ключу словаря uploaded и применим метод .decode()
# uploaded_str = uploaded['titanic.csv'].decode()

# на выходе получаем обычную строку
# print(type(uploaded_str))

In [108]:
# выведем первые 100 символов
# print(uploaded_str[:100])

In [109]:
# если разбить строку методом .split() по символам \r (возврат к началу строки) и \n (новая строка)
# uploaded_list = uploaded_str.split('\r\n')

# на выходе мы получим список
# type(uploaded_list)

In [110]:
# # пройдемся по этому списку, не забыв создать индекс с помощью функции enumerate()
# for i, line in enumerate(uploaded_list):

#   # начнем выводить записи
#   print(line)

#   # когда дойдем до четвертой строки
#   if i == 3:

#     # прервемся
#     break

#### Чтение через библиотеку Pandas

In [111]:
# pd.read_csv?

In [192]:
# импортируем библиотеку
import pandas as pd

# применим функцию read_csv() и посмотрим на первые три записи файла titanic.csv
# sep - запятая, encoding - utf-8, строки ("", ''), даты (2015-01-01), числа (с точкой)
df = pd.read_csv('/content/titanic.csv', sep=',') # объект DataFrame
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

### Этап 3. Исследовательский анализ данных (EDA)

1. Смотрим что за данные достались (размер, типы столбцов, хватает ли данных)
2. Проанализировать числовые значения в данных (пропуски null, NaN, нулевые значения, выбросы - как распределены и нет ли выбросов, распределения, мин и макс, квартили/квантили/персентили)
3. Текстовые данные - обработка и решение исключать или нет (категориальные данные)
4. Можно ли из текстовых данных выделить столбцы с 2 значениями - да/нет, муж/жен, есть/нет. "Легкие" категориальные данные. Их можно преобразовать в True/False, boolean, 1/0

In [113]:
?df.info

In [193]:
# посмотрим на данные в целом
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [194]:
df['PassengerId'] = df['PassengerId'].astype('int32')

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int32
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int32(1), int64(4), object(5)
memory usage: 80.2+ KB

In [115]:
df.memory_usage()

Index           128
PassengerId    7128
Survived       7128
Pclass         7128
Name           7128
Sex            7128
Age            7128
SibSp          7128
Parch          7128
Ticket         7128
Fare           7128
Cabin          7128
Embarked       7128
dtype: int64

In [116]:
# посмотрим на данные в целом
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 315.0 KB

Пропущенные значения

In [117]:
# выявим пропущенные значения с помощью .isnull() и посчитаем их количество через sum()
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [118]:
# выявим пропущенные значения с помощью .isnull() и посчитаем их долю через mean()
df.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [119]:
# переменная Cabin (номер каюты), скорее всего, не является самой важной
# избавимся от нее с помощью метода .drop()
# (параметр axis = 1 отвечает за столбцы, inplace = True сохраняет изменения)
df.drop(columns = 'Cabin', axis = 1, inplace = True)

In [120]:
# выявим пропущенные значения с помощью .isnull() и посчитаем их долю через mean()
df.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Embarked       0.002245
dtype: float64

In [121]:
df.drop(columns = 'Age', axis = 1)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,Q

In [122]:
df.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Embarked       0.002245
dtype: float64

In [123]:
# а вот Age (возраст) скорее важен, заменим пустые значения средним арифметическим
df['Age'].fillna(df['Age'].mean(), inplace = True) #fillna меняет исходную таблицу только с inplace = True

In [124]:
df.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Embarked       0.002245
dtype: float64

In [125]:
# у нас остаются две пустые строки в Embarked, удалим их
df.dropna(inplace = True)

In [126]:
df.shape

(889, 11)

In [127]:
# посмотрим на результат
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Категориальные переменные

In [128]:
# применим one-hot encoding к переменной Sex (пол) с помощью функции pd.get_dummies()
# head(3) -  первые 3 строки
pd.get_dummies(df['Sex']).head(3) # замена значений на True, False

   female   male
0   False   True
1    True  False
2    True  False

In [129]:
# снова скачаем столбец Sex из датасета train в формате датафрейма
previous = pd.read_csv('/content/titanic.csv')[['Sex']]
previous.head() # по умолчанию первеы 5 строк

      Sex
0    male
1  female
2  female
3  female
4    male

In [130]:
pd.get_dummies?

In [131]:
# закодируем переменную через 0 и 1
pd.get_dummies(previous['Sex'], dtype = int).head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [132]:
# удалим первый столбец, он избыточен
sex = pd.get_dummies(df['Sex'], drop_first = True)
sex.head(3)

    male
0   True
1  False
2  False

In [133]:
# сделаем то же самое для переменных Pclass и Embarked
embarked = pd.get_dummies(df['Embarked'], drop_first = True)
pclass = pd.get_dummies(df['Pclass'], drop_first = True)

In [134]:
# присоединим закодированные через one-hot encoding переменные
# к исходному датафрейму через функцию .concat()
df = pd.concat([df, pclass, sex, embarked], axis = 1)
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,2,3,male,Q,S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,False,True,True,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,False,False,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,False,True,False,False,True

Отбор признаков

In [135]:
# удалим те столбцы, которые нам теперь не нужны
df.drop(['PassengerId', 'Pclass', 'Name', 'Sex', 'Ticket', 'Embarked'], axis = 1, inplace = True)
df.head(3)

   Survived   Age  SibSp  Parch     Fare      2      3   male      Q      S
0         0  22.0      1      0   7.2500  False   True   True  False   True
1         1  38.0      1      0  71.2833  False  False  False  False  False
2         1  26.0      0      0   7.9250  False   True  False  False   True

Нормализация данных

In [136]:
# импортируем класс StandardScaler
from sklearn.preprocessing import StandardScaler

# создадим объект этого класса
scaler = StandardScaler()

# выберем те столбцы, которые мы хотим масштабировать
cols_to_scale = ['Age', 'Fare']

# рассчитаем среднее арифметическое и СКО для масштабирования данных
scaler.fit(df[cols_to_scale])

# применим их
df[cols_to_scale] = scaler.transform(df[cols_to_scale])

# посмотрим на результат
df.head(3)

,Survived,Age,SibSp,Parch,Fare,2,3,male,Q,S
0,0,-0.590495,1,0,-0.500240,False,True,True,False,True
1,1,0.643971,1,0,0.788947,False,False,False,False,False
2,1,-0.281878,0,0,-0.486650,False,True,False,False,True

In [137]:
# некоторые названия столбцов теперь представляют собой числа, так быть не должно
df.columns

Index(['Survived', 'Age', 'SibSp', 'Parch', 'Fare', 2, 3, 'male', 'Q', 'S'], dtype='object')

In [138]:
# преобразуем эти переменные в тип str через функцию map()
df.columns = df.columns.map(str)
df.columns

Index(['Survived', 'Age', 'SibSp', 'Parch', 'Fare', '2', '3', 'male', 'Q',
       'S'],
      dtype='object')

### Этап 4. Сохранение нового файла на сервере Google

In [139]:
# создадим новый файл result.csv с помощью функции to_csv(), удалив при этом индекс
df.to_csv('/content/result.csv', index = False)

# файл будет сохранен в 'Сессионном хранилище' и, если все пройдет успешно, выведем следующий текст:
print('Файл успешно сохранился в сессионное хранилище!')

Файл успешно сохранился в сессионное хранилище!

### Этап 5. Скачивание обратно на жесткий диск

In [140]:
# применим метод .download() объекта files
files.download('/content/result.csv')

## Исследование Титаника

### Загрузим библиотеки

In [141]:
import pandas as pd
import numpy as np

In [142]:
df = pd.read_csv('/content/titanic.csv') #подгрузим файл
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [143]:
print(df.shape) # сколько строк и столбцов

(891, 12)

In [144]:
df_rows, df_cols = df.shape
print(f'Столбцов в наборе данных: {df_cols}')
print(f'Строк в наборе данных: {df_rows}')

Столбцов в наборе данных: 12
Строк в наборе данных: 891

In [145]:
df.columns # названия колонок, признаки

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Если названия колонок трудночитаемы, то стоит их изменить

In [146]:
df.info?

In [147]:
df.info(memory_usage='deep') # общая информация оценкой по памяти

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 315.0 KB

In [148]:
df.memory_usage() # размер байтов занимает каждая колонка

Index           128
PassengerId    7128
Survived       7128
Pclass         7128
Name           7128
Sex            7128
Age            7128
SibSp          7128
Parch          7128
Ticket         7128
Fare           7128
Cabin          7128
Embarked       7128
dtype: int64

In [149]:
df.isnull().sum() # поиск пропусков

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [150]:
df.dropna(inplace=True,axis=0,subset=['Cabin']) # удаление пропусков

In [151]:
df['Age'].fillna(df['Age'].mean(), inplace = True) # удаление пропусков

In [152]:
print(df.shape) # размер без пропусков

(204, 12)

In [153]:
# передадим в параметр columns тот столбец, который хотим удалить
df.drop(columns = ['Cabin'], inplace=True)

In [154]:
df.isnull().sum() #проверим на пустые значения

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [155]:
print(df.shape) # размер без пропусков

(204, 11)

In [156]:
df.isnull().sum() #проверим на пустые значения

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [157]:
df.dropna(inplace=True,axis=0,subset=['Embarked']) # удаление пропусков

In [158]:
df.isnull().sum() #проверим на пустые значения

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [159]:
df.describe?

In [160]:
df.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9])

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000
mean,455.495050,0.663366,1.198020,35.688993,0.445545,0.440594,76.103301
std,249.704228,0.473732,0.528205,14.886197,0.630490,0.732294,74.759941
min,2.000000,0.000000,1.000000,0.920000,0.000000,0.000000,0.000000
10%,111.800000,0.000000,1.000000,18.000000,0.000000,0.000000,13.000000
25%,263.250000,0.000000,1.000000,25.000000,0.000000,0.000000,28.959375
50%,457.500000,1.000000,1.000000,35.829297,0.000000,0.000000,55.000000
75%,681.500000,1.000000,1.000000,46.750000,1.000000,1.000000,89.776050
90%,782.900000,1.000000,2.000000,55.900000,1.000000,2.000000,153.271250
max,890.000000,1.000000,3.000000,80.000000,3.000000,4.000000,512.329200

In [161]:
df.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9]).T

,count,mean,std,min,10%,25%,50%,75%,90%,max
PassengerId,202.0,455.495050,249.704228,2.00,111.8,263.250000,457.500000,681.50000,782.90000,890.0000
Survived,202.0,0.663366,0.473732,0.00,0.0,0.000000,1.000000,1.00000,1.00000,1.0000
Pclass,202.0,1.198020,0.528205,1.00,1.0,1.000000,1.000000,1.00000,2.00000,3.0000
Age,202.0,35.688993,14.886197,0.92,18.0,25.000000,35.829297,46.75000,55.90000,80.0000
SibSp,202.0,0.445545,0.630490,0.00,0.0,0.000000,0.000000,1.00000,1.00000,3.0000
Parch,202.0,0.440594,0.732294,0.00,0.0,0.000000,0.000000,1.00000,2.00000,4.0000
Fare,202.0,76.103301,74.759941,0.00,13.0,28.959375,55.000000,89.77605,153.27125,512.3292

In [162]:
type(df.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9]))

pandas.core.frame.DataFrame

### Сколько мужчин было на корабле:

In [163]:
df['Sex'] == 'male'

1      False
3      False
6       True
10     False
11     False
       ...
871    False
872     True
879    False
887    False
889     True
Name: Sex, Length: 202, dtype: bool

In [164]:
df[df['Sex'] == 'male']['Sex'].count() # посчитать кличество по условию

107

In [165]:
df[df['Sex'] == 'female']['Sex'].count() # посчитать кличество по условию

95

### Доля выживших пассажиров (в %):

In [166]:
df['Survived'].sum() / df['Survived'].count() * 100

66.33663366336634

In [167]:
df['Survived'].mean() * 100

66.33663366336634

### Доля пассажиров (в %) второго класса:

In [168]:
df[df['Pclass'] == 2]['Pclass'].count() / df['Pclass'].count() * 100

7.920792079207921

In [169]:
df[df['Pclass'] == 1]['Pclass'].count() / df['Pclass'].count() * 100

86.13861386138613

### Среднее значение возраста всех людей на корабле:

In [170]:
df['Age'].mean() # среднее

35.688993310141825

Медиана возраста всех людей на корабле:

In [171]:
df['Age'].median() # медиана

35.829297297297295

In [172]:
df['Age'].max() # max

80.0

### Самое популярное женское имя на корабле. (Извлечь из полного имени FirstName)

In [173]:
first_names = list()
value_dict = {'(' : '', ')' : ''}
for x in df['Name']:
  first_names.append(x.split(" ")[2].replace('(', ''))

df.insert(loc=len(df.columns), column='Names', value=first_names)

In [174]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Names
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C,John
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S,Jacques
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,S,Timothy
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.000000,1,1,PP 9549,16.7000,S,Marguerite
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.000000,0,0,113783,26.5500,S,Elizabeth
21,22,1,2,"Beesley, Mr. Lawrence",male,34.000000,0,0,248698,13.0000,S,Lawrence
23,24,1,1,"Sloper, Mr. William Thompson",male,28.000000,0,0,113788,35.5000,S,William
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.000000,3,2,19950,263.0000,S,Charles
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,35.829297,1,0,PC 17569,146.5208,C,William
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.000000,1,0,PC 17572,76.7292,C,Henry

In [175]:
df[df['Sex'] == 'female']['Names'].value_counts(normalize=False)

Names
Elizabeth    5
John         4
William      4
Amelia       3
Frederick    3
            ..
Frank        1
Jacques      1
Marjorie     1
Hjalmar      1
Richard      1
Name: count, Length: 72, dtype: int64

In [176]:
pd.crosstab(df['Sex'], df['Pclass'], normalize=False)

Pclass   1   2  3
Sex
female  79  10  6
male    95   6  6

### Типы столбцов и гипотезы

In [177]:
# разделить на категориальные признаки и количественные
# провести анализ по ним

a)Сколько столбцов и сколько строк в сохраненном DataFrame

In [178]:
count = df.shape #кортеж из количества строк и столбцов
print(f'количество строк - {count[0]}, количество столбцов - {count[1]}')

количество строк - 202, количество столбцов - 12

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 202 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  202 non-null    int64
 1   Survived     202 non-null    int64
 2   Pclass       202 non-null    int64
 3   Name         202 non-null    object
 4   Sex          202 non-null    object
 5   Age          202 non-null    float64
 6   SibSp        202 non-null    int64
 7   Parch        202 non-null    int64
 8   Ticket       202 non-null    object
 9   Fare         202 non-null    float64
 10  Embarked     202 non-null    object
 11  Names        202 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 20.5+ KB

b)Какой объем памяти занимает DataFrame

In [180]:
memory_usage = df.memory_usage(deep=True).sum() #df.memory_usage() возвращает использование памяти каждым столбцом в байтах
print(f'Объем памяти, занимаемый DataFrame: {memory_usage} байт')

Объем памяти, занимаемый DataFrame: 80323 байт

c)Сколько столбцов разных типов

In [181]:
dtype_counts = df.dtypes.value_counts() #подсчет количества столбцов каждого типа данных.
print(f'всего столбцов разных типов - {len(dtype_counts)}')

всего столбцов разных типов - 3

In [182]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 202 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  202 non-null    int64
 1   Survived     202 non-null    int64
 2   Pclass       202 non-null    int64
 3   Name         202 non-null    object
 4   Sex          202 non-null    object
 5   Age          202 non-null    float64
 6   SibSp        202 non-null    int64
 7   Parch        202 non-null    int64
 8   Ticket       202 non-null    object
 9   Fare         202 non-null    float64
 10  Embarked     202 non-null    object
 11  Names        202 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 20.5+ KB

2)приведение названий всех столбцов к виду с маленькими буквами на английском языке без пробелов

In [183]:
df.columns = [col.lower().replace(' ','') for col in df.columns]
print(*df.columns,sep = ', ')

passengerid, survived, pclass, name, sex, age, sibsp, parch, ticket, fare, embarked, names

In [184]:
features_names = df.columns.tolist()
features_names

['passengerid',
 'survived',
 'pclass',
 'name',
 'sex',
 'age',
 'sibsp',
 'parch',
 'ticket',
 'fare',
 'embarked',
 'names']

3)Вывести статистику по каждому столбцу:

a)для категориальных переменных: количество уникальных значений, моду,
количество пропущенных значений

include=['object'] - выделить категориальную переменную

In [185]:
category_cols = df.select_dtypes(include=['object']) #выбрали столбцы с категориальными переменными
category_cols_names = category_cols.columns.tolist()
print(f'категориальные столбцы: {category_cols_names}\n')
for col in category_cols_names:
    print(f'информация о столбце {col}:')
    print(f'количество уникальных значений: {category_cols[col].nunique()}') #для кол-ва уникальных волспользуемся функцией nunique()
    print(f'мода: {category_cols[col].mode().tolist()}') #для поиска моды - функцией mode() (Если в столбце несколько значений встречаются одинаковое количество раз, метод mode() вернет все такие значения.)
    print(f'количество пропущенных значений: {category_cols[col].isna().sum()}\n') #isna() - создания булевой маски, которая указывает, какие ячейки в столбце содержат пропущенные значения, sum() используется для подсчета количества True значений в маске

категориальные столбцы: ['name', 'sex', 'ticket', 'embarked', 'names']

информация о столбце name:
количество уникальных значений: 202
мода: ['Allen, Miss. Elisabeth Walton', 'Allison, Master. Hudson Trevor', 'Allison, Miss. Helen Loraine', 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)', 'Anderson, Mr. Harry', 'Andrews, Miss. Kornelia Theodosia', 'Andrews, Mr. Thomas Jr', 'Appleton, Mrs. Edward Dale (Charlotte Lamson)', 'Astor, Mrs. John Jacob (Madeleine Talmadge Force)', 'Aubart, Mme. Leontine Pauline', 'Ball, Mrs. (Ada E Hall)', 'Barkworth, Mr. Algernon Henry Wilson', 'Baxter, Mr. Quigg Edmond', 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)', 'Bazzani, Miss. Albina', 'Becker, Master. Richard F', 'Becker, Miss. Marion Louise', 'Beckwith, Mr. Richard Leonard', 'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)', 'Beesley, Mr. Lawrence', 'Behr, Mr. Karl Howell', 'Bishop, Mr. Dickinson H', 'Bishop, Mrs. Dickinson H (Helen Walton)', 'Bissette, Miss. Amelia', 'Bjornstrom-Steffansson, Mr. Mauritz Hakan', 'Blackwell, Mr. Stephen Weart', 'Blank, Mr. Henry', 'Bonnell, Miss. Elizabeth', 'Bowerman, Miss. Elsie Edith', 'Brown, Miss. Amelia "Mildred"', 'Brown, Mrs. James Joseph (Margaret Tobin)', 'Burns, Miss. Elizabeth Margaret', 'Butt, Major. Archibald Willingham', 'Calderhead, Mr. Edward Pennington', 'Cardeza, Mr. Thomas Drake Martinez', 'Carlsson, Mr. Frans Olof', 'Carter, Master. William Thornton II', 'Carter, Miss. Lucile Polk', 'Carter, Mr. William Ernest', 'Carter, Mrs. William Ernest (Lucile Polk)', 'Cavendish, Mr. Tyrell William', 'Chaffee, Mr. Herbert Fuller', 'Chambers, Mr. Norman Campbell', 'Chambers, Mrs. Norman Campbell (Bertha Griggs)', 'Cherry, Miss. Gladys', 'Chibnall, Mrs. (Edith Martha Bowerman)', 'Clifford, Mr. George Quincy', 'Colley, Mr. Edward Pomeroy', 'Compton, Miss. Sara Rebecca', 'Crosby, Capt. Edward Gifford', 'Crosby, Miss. Harriet R', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Daly, Mr. Peter Denis ', 'Davidson, Mr. Thornton', 'Dick, Mr. Albert Adrian', 'Dick, Mrs. Albert Adrian (Vera Gillespie)', 'Dodge, Master. Washington', 'Douglas, Mr. Walter Donald', 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")', 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")', 'Endres, Miss. Caroline Louise', 'Eustis, Miss. Elizabeth Mussey', 'Farthing, Mr. John', 'Flynn, Mr. John Irwin ("Irving")', 'Foreman, Mr. Benjamin Laventall', 'Fortune, Miss. Alice Elizabeth', 'Fortune, Miss. Mabel Helen', 'Fortune, Mr. Charles Alexander', 'Fortune, Mr. Mark', 'Francatelli, Miss. Laura Mabel', 'Frolicher, Miss. Hedwig Margaritha', 'Frolicher-Stehli, Mr. Maxmillian', 'Fry, Mr. Richard', 'Futrelle, Mr. Jacques Heath', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Gee, Mr. Arthur H', 'Giglio, Mr. Victor', 'Goldenberg, Mr. Samuel L', 'Goldenberg, Mrs. Samuel L (Edwiga Grabowska)', 'Goldschmidt, Mr. George B', 'Graham, Miss. Margaret Edith', 'Graham, Mr. George Edward', 'Graham, Mrs. William Thompson (Edith Junkins)', 'Greenfield, Mr. William Bertram', 'Guggenheim, Mr. Benjamin', 'Harder, Mr. George Achilles', 'Harper, Mr. Henry Sleeper', 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'Harris, Mr. Henry Birkhardt', 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 'Harrison, Mr. William', 'Hassab, Mr. Hammad', 'Hawksford, Mr. Walter James', 'Hays, Miss. Margaret Bechstein', 'Hays, Mrs. Charles Melville (Clara Jennings Gregg)', 'Hippach, Miss. Jean Gertrude', 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)', 'Hogeboom, Mrs. John C (Anna Andrews)', 'Hoyt, Mr. Frederick Maxfield', 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)', 'Humblen, Mr. Adolf Mathias Nicolai Olsen', 'Isham, Miss. Ann Elizabeth', 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)', 'Keane, Miss. Nora A', 'Kent, Mr. Edward Austin', 'Kenyon, Mrs. Frederick R (Marion)', 'Kimball, Mr. Edwin Nelson Jr', 'Klaber, Mr. Herman', 'Leader, Dr. Alice (Farnham)', 'Lemore, Mrs. (Amelia Milley)', 'Lesurer, Mr. Gustave J', 'Levy, Mr. Rene Jacques', 'Lines, Miss. Mary Conover', 'Long, Mr. Milton Clyde', 'Longley, Miss. Gretchen Fiske', 'Lurette, Miss. Elise', 'Mack, Mrs. (Mary)', 'Madill, Miss. Georgette Alexandra', 'Maioni, Miss. Roberta', 'Marechal, Mr. Pierre', 'Marvin, Mr. Daniel Warner', 'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")', 'McCarthy, Mr. Timothy J', 'McGough, Mr. James Robert', 'Millet, Mr. Francis Davis', 'Minahan, Dr. William Edward', 'Minahan, Miss. Daisy E', 'Moen, Mr. Sigurd Hansen', 'Molson, Mr. Harry Markland', 'Moor, Master. Meier', 'Moor, Mrs. (Beila)', 'Natsch, Mr. Charles H', 'Navratil, Master. Edmond Roger', 'Navratil, Master. Michel M', 'Navratil, Mr. Michel ("Louis M Hoffman")', 'Newell, Miss. Madeleine', 'Newell, Miss. Marjorie', 'Newell, Mr. Arthur Webster', 'Newsom, Miss. Helen Monypeny', 'Nye, Mrs. (Elizabeth Ramell)', 'Ostby, Mr. Engelhart Cornelius', 'Partner, Mr. Austen', 'Pears, Mr. Thomas Clinton', 'Pears, Mrs. Thomas (Edith Wearne)', 'Penasco y Castellana, Mr. Victor de Satode', 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)', 'Perreault, Miss. Anne', 'Peter, Miss. Anna', 'Peuchen, Major. Arthur Godfrey', 'Pickard, Mr. Berk (Berk Trembisky)', 'Porter, Mr. Walter Chamberlain', 'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)', 'Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)', 'Roebling, Mr. Washington Augustus II', 'Rood, Mr. Hugh Roscoe', 'Ross, Mr. John Hugo', 'Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)', 'Ryerson, Miss. Emily Borie', 'Ryerson, Miss. Susan Parker "Suzette"', 'Saalfeld, Mr. Adolphe', 'Sagesser, Mlle. Emma', 'Sandstrom, Miss. Marguerite Rut', 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)', 'Shutes, Miss. Elizabeth W', 'Silverthorne, Mr. Spencer Victor', 'Silvey, Mr. William Baird', 'Silvey, Mrs. William Baird (Alice Munger)', 'Simonius-Blumer, Col. Oberst Alfons', 'Sloper, Mr. William Thompson', 'Smith, Mr. James Clinch', 'Smith, Mr. Richard William', 'Soholt, Mr. Peter Andreas Lauritz Andersen', 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)', 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'Stahelin-Maeglin, Dr. Max', 'Stead, Mr. William Thomas', 'Stephenson, Mrs. Walter Bertram (Martha Eustis)', 'Strom, Miss. Telma Matilda', 'Strom, Mrs. Wilhelm (Elna Matilda Persson)', 'Sutton, Mr. Frederick', 'Swift, Mrs. Frederick Joel (Margaret Welles Barron)', 'Taussig, Miss. Ruth', 'Taussig, Mr. Emil', 'Taussig, Mrs. Emil (Tillie Mandelbaum)', 'Taylor, Mr. Elmer Zebley', 'Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)', 'Thayer, Mr. John Borland', 'Thayer, Mr. John Borland Jr', 'Thayer, Mrs. John Borland (Marian Longstreth Morris)', 'Tobin, Mr. Roger', 'Troutt, Miss. Edwina Celia "Winnie"', 'Van der hoef, Mr. Wyckoff', 'Walker, Mr. William Anderson', 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)', 'Webber, Miss. Susan', 'White, Mr. Percival Wayland', 'White, Mr. Richard Frasar', 'Wick, Miss. Mary Natalie', 'Widener, Mr. Harry Elkins', 'Williams-Lambert, Mr. Fletcher Fellows', 'Woolner, Mr. Hugh', 'Young, Miss. Marie Grice']
количество пропущенных значений: 0

информация о столбце sex:
количество уникальных значений: 2
мода: ['male']
количество пропущенных значений: 0

информация о столбце ticket:
количество уникальных значений: 141
мода: ['113760', '19950']
количество пропущенных значений: 0

информация о столбце embarked:
количество уникальных значений: 3
мода: ['S']
количество пропущенных значений: 0

информация о столбце names:
количество уникальных значений: 120
мода: ['William']
количество пропущенных значений: 0

In [186]:
df.describe(include='object')

,name,sex,ticket,embarked,names
count,202,202,202,202,202
unique,202,2,141,3,120
top,"Cumings, Mrs. John Bradley (Florence Briggs Th...",male,113760,S,William
freq,1,107,4,129,13

b)Для интервальных: медиану, среднее, квантиль 90, квантиль 10, максимальное значение, минимальное значение, количество пропущенных значений

In [187]:
category_int = df.select_dtypes(include=['int64','float64']) #выбрали столбцы с интервальные переменными
category_int_names = category_int.columns.tolist()
print(f'интервальные столбцы: {category_int_names}\n')

for col in category_int_names:
    print(f'информация о столбце {col}:')
    print(f'медиана: {category_int[col].median()}')
    print(f'среднее: {category_int[col].mean()}')
    print(f'квантиль 90: {category_int[col].quantile(0.9)}')
    print(f'квантиль 10: {category_int[col].quantile(0.1)}')
    print(f'максимум: {category_int[col].max()}')
    print(f'минимум: {category_int[col].min()}')
    print(f'кол-во пропусков: {category_int[col].isna().sum()}\n')

интервальные столбцы: ['passengerid', 'survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']

информация о столбце passengerid:
медиана: 457.5
среднее: 455.4950495049505
квантиль 90: 782.9
квантиль 10: 111.80000000000001
максимум: 890
минимум: 2
кол-во пропусков: 0

информация о столбце survived:
медиана: 1.0
среднее: 0.6633663366336634
квантиль 90: 1.0
квантиль 10: 0.0
максимум: 1
минимум: 0
кол-во пропусков: 0

информация о столбце pclass:
медиана: 1.0
среднее: 1.198019801980198
квантиль 90: 2.0
квантиль 10: 1.0
максимум: 3
минимум: 1
кол-во пропусков: 0

информация о столбце age:
медиана: 35.829297297297295
среднее: 35.688993310141825
квантиль 90: 55.900000000000006
квантиль 10: 18.0
максимум: 80.0
минимум: 0.92
кол-во пропусков: 0

информация о столбце sibsp:
медиана: 0.0
среднее: 0.44554455445544555
квантиль 90: 1.0
квантиль 10: 0.0
максимум: 3
минимум: 0
кол-во пропусков: 0

информация о столбце parch:
медиана: 0.0
среднее: 0.4405940594059406
квантиль 90: 2.0
квантиль 10: 0.0
максимум: 4
минимум: 0
кол-во пропусков: 0

информация о столбце fare:
медиана: 55.0
среднее: 76.10330099009902
квантиль 90: 153.27125
квантиль 10: 13.0
максимум: 512.3292
минимум: 0.0
кол-во пропусков: 0

In [188]:
df.describe(percentiles=[0.1, 0.5, 0.9], include=['int64','float64'])

,passengerid,survived,pclass,age,sibsp,parch,fare
count,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000
mean,455.495050,0.663366,1.198020,35.688993,0.445545,0.440594,76.103301
std,249.704228,0.473732,0.528205,14.886197,0.630490,0.732294,74.759941
min,2.000000,0.000000,1.000000,0.920000,0.000000,0.000000,0.000000
10%,111.800000,0.000000,1.000000,18.000000,0.000000,0.000000,13.000000
50%,457.500000,1.000000,1.000000,35.829297,0.000000,0.000000,55.000000
90%,782.900000,1.000000,2.000000,55.900000,1.000000,2.000000,153.271250
max,890.000000,1.000000,3.000000,80.000000,3.000000,4.000000,512.329200